plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            data()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()

        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    // Add here additional repositories if required by some of the dependencies below.
    maven { url 'https://maven.terraformersmc.com/' }
}

dependencies {
    implementation 'maven.modrinth:patched:7.3.3+1.21.1-neoforge'
    compileOnly "com.terraformersmc:biolith-neoforge:$biolith_version"

    //Optional Dependencies
    runtimeOnly "curse.maven:regions-unexplored-659110:7492526"
    runtimeOnly "curse.maven:natures-spirit-1044992:6962784"
    runtimeOnly "curse.maven:terrablender-neoforge-940057:6054947"
    runtimeOnly "curse.maven:expanded-ecosphere-490686:7294363"
    runtimeOnly "curse.maven:cristel-lib-856996:7233453"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }
