package com.elephantaugments.projectevergreen.common;

import com.elephantaugments.projectevergreen.common.api.PEStructure;
import com.elephantaugments.projectevergreen.common.data.defaults.DefaultFlags;

import java.util.*;

public class Constants {

	public static final List<String> EMPTY_LIST = new ArrayList<>();

	public static final int OVERWORLD_DIFFICULTY = 3;
	public static final int OTHERWORLD_DIFFICULTY = 4;

	public static final int NETHER_DIFFICULTY_OFFSET = 1;
	public static final int AETHER_DIFFICULTY_OFFSET = 1;
	public static final int END_DIFFICULTY_OFFSET = 3;
	public static final int AFTERDARK_DIFFICULTY_OFFSET = 2;
	public static final int LOSTCITIES_DIFFICULTY_OFFSET = 4;

	public static final int SAFE_DIFFICULTY_OFFSET = -2;
	public static final int NEUTRAL_DIFFICULTY_OFFSET = 0;
	public static final int DANGEROUS_DIFFICULTY_OFFSET = 2;

	public static final int DEFAULT_DECO_SPACING = 12;
	public static final int DEFAULT_DECO_SEPARATION = 6;
	public static final int DEFAULT_MEDIUM_SPACING = 24;
	public static final int DEFAULT_MEDIUM_SEPARATION = 16;
	public static final int DEFAULT_MASSIVE_SPACING = 42;
	public static final int DEFAULT_MASSIVE_SEPARATION = 34;
	public static final int DEFAULT_SPRAWLING_SPACING = 64;
	public static final int DEFAULT_SPRAWLING_SEPARATION = 58;
	public static final Double CIVILIZATION_SPREAD_OFFSET = 0.85;
	public static final Double WILDERNESS_SPREAD_OFFSET = 1.25;
	public static final Double SPECIAL_SPREAD_OFFSET = 1.35;
	public static final Double FLATNESS_SPREAD_OFFSET = 0.65;

	public static final String BIOME_TAG_PATH = "tags/worldgen/biome/";
	public static final String STRUCTURE_TAG_PATH = "tags/worldgen/structure/";
	public static final String STRUCTURE_SET_TAG_PATH = "tags/worldgen/structure_set/";
	public static final String ENTITY_TAG_PATH = "tags/entity_type/";

	public static final String ID_TAG = "structure_id";
	public static final String BIOME_TAG = "biome_tag";
	public static final String LOADED_STRUCTURES_KEY = "loadedStructures";
	public static final String FLAT_STRUCTURES_KEY = "loadedFlatStructures";
	public static final String IS_BIOME_REGISTERED_TEST = "is_biome_loaded";
    public static final String UNDERGROUND_STRUCTURES_KEY = "loadedUndergroundStructures";
	public static final String PERFORMANCE_CONFIG_VALUE = "performance_friendly_mode";
	public static final String PERFORMANCE_MODE_CONFIG = ProjectEvergreen.MODID + ":performance_mode";
	public static final String STRUCTURE_BIOME_TOGGLE = "structure_biome_redistribution";
	public static final String STRUCTURE_BIOME_REDISTRIBUTION = ProjectEvergreen.MODID + ":structure_biome_redistribution";
	public static final String STRUCTURE_RARITY_TOGGLE = "structure_rarity_redistribution";
	public static final String STRUCTURE_RARITY_REDISTRIBUTION = ProjectEvergreen.MODID + ":structure_rarity_redistribution";
	public static final String INLAND_STRUCTURE_TEST = ProjectEvergreen.MODID + ":inland_structure";
	public static final String WATER_STRUCTURE_TEST = ProjectEvergreen.MODID + ":water_structure";
	public static final String MASSIVE_STRUCTURE_TEST = ProjectEvergreen.MODID + ":massive_structure";
	public static final String SAFE_STRUCTURE_TYPE = ProjectEvergreen.MODID + ":safe_structure_type";
	public static final String ADVANCED_STRUCTURE_TYPE = ProjectEvergreen.MODID + ":advanced_structure_type";
	public static final String ENHANCED_TERRAIN_ADAPTATION = "enhanced_terrain_adaption";
	public static final String TERRAIN_ADAPTATION_TEST = ProjectEvergreen.MODID + ":" + ENHANCED_TERRAIN_ADAPTATION;
	public static final String IGNORE_BIOME_REDISTRIBUTION_TEST = ProjectEvergreen.MODID + ":" + PEStructure.Flag.IGNORED_BIOME_REDISTRIBUTION.name();
	public static final String IGNORE_BIOME_RADIUS_TEST = ProjectEvergreen.MODID + ":" + PEStructure.Flag.IGNORE_BIOME_RADIUS_CHECK.name();
	public static final String POPULATION_BIAS_TEST = ProjectEvergreen.MODID + ":population_bias_check";
	public static final String ALLOWED_TERRAIN_HEIGHT_NARROW = "narrow_flatness_allowed_elevation";
	public static final String FLAT_NARROW_TEST = ProjectEvergreen.MODID + ":flat_check_narrow";
	public static final String ALLOWED_TERRAIN_HEIGHT_WIDE = "wide_flatness_allowed_elevation";
	public static final String FLAT_WIDE_TEST = ProjectEvergreen.MODID + ":flat_check_wide";
	public static final String ALLOWED_TERRAIN_HEIGHT_SPRAWLING = "sprawling_flatness_allowed_elevation";
	public static final String FLAT_SPRAWLING_TEST = ProjectEvergreen.MODID + ":" + PEStructure.Flag.FLATNESS_CHECK_SPRAWLING.name();
	public static final String IGNORE_FLATNESS_CHECK_TEST = ProjectEvergreen.MODID + ":flatness_check_ignored";
	public static final String FLATNESS_CHECK_SPRAWLING = "flatness_check_sprawling";
	public static final String FLATNESS_CHECK_LARGE = "flatness_check_large";
	public static final String FLATNESS_CHECK_SMALL = "flatness_check_small";

	public static final String IGNORE_MOD = "ignore_mods";
	public static final String IGNORE_STRUCTURE = "ignore_structures";
	public static final String IGNORE_STRUCTURE_TYPE = "ignore_structure_type";
	public static final String IGNORE_BIOME_REDISTRIBUTION = "ignore_biome_redistribution";
	public static final String IGNORE_BIOME_RADIUS = "ignore_biome_radius";
	public static final String IGNORE_WATER_RESTRICTION = "ignore_water_restriction";
	public static final String IGNORE_FLATNESS_CHECK = "ignore_flatness_check";
	public static final String IGNORE_TERRAIN_ADAPTATION = "ignore_terrain_adaptation";

	public static final String POPULATION_BIAS = "population_bias";
	public static final String POPULATION_BIAS_OFFSET = "population_bias_offset";
	public static final String CIVILIZATION_MASSIVE_RARITY = "civilization_massive_rarity";
	public static final String CIVILIZATION_MEDIUM_RARITY = "civilization_medium_rarity";
	public static final String CIVILIZATION_DECORATIVE_RARITY = "civilization_decorative_rarity";
	public static final String WILDERNESS_MASSIVE_RARITY = "wilderness_massive_rarity";
	public static final String WILDERNESS_MEDIUM_RARITY = "wilderness_medium_rarity";
	public static final String WILDERNESS_DECORATIVE_RARITY = "wilderness_decorative_rarity";
	public static final String UNDERGROUND_MASSIVE_RARITY = "underground_massive_rarity";
	public static final String OCEAN_MASSIVE_RARITY = "ocean_massive_rarity";
	public static final String OCEAN_MEDIUM_RARITY = "ocean_medium_rarity";
	public static final String SKY_MASSIVE_RARITY = "sky_massive_rarity";

	public static final String CIVILIZATION_MASSIVE = "civilization_inland_massive";
	public static final String CIVILIZATION_MEDIUM = "civilization_inland_medium";
	public static final String CIVILIZATION_DECO = "civilization_inland_deco";
    public static final String WILDERNESS_MASSIVE = "wilderness_inland_massive";
    public static final String WILDERNESS_MEDIUM = "wilderness_inland_medium";
    public static final String WILDERNESS_DECO = "wilderness_inland_deco";
    public static final String OCEAN_FLOATING_MASSIVE = "ocean_floating_massive";
    public static final String OCEAN_UNDERWATER_MASSIVE = "ocean_underwater_massive";
    public static final String OCEAN_ALL_MEDIUM = "ocean_all_medium";
    public static final String UNDERGROUND_MASSIVE = "underground_massive";
    public static final String SKY_MASSIVE = "sky_massive";

	public static final String NO_BIOMES = "no_biomes";
    public static final String ALL_OCEAN = "all_ocean";
    public static final String ALL_RIVERS = "all_rivers";
    public static final String ALL_CIVILIZATION = "all_civilization";
    public static final String ALL_WILDERNESS = "all_wilderness";
    public static final String CIVILIZATION_TEMPERATE = "civilization_temperate";
    public static final String CIVILIZATION_FIELDS = "civilization_fields";
    public static final String CIVILIZATION_CONIFEROUS = "civilization_coniferous";
    public static final String CIVILIZATION_DECIDUOUS = "civilization_deciduous";
    public static final String CIVILIZATION_ARID = "civilization_arid";
    public static final String CIVILIZATION_DESERT = "civilization_desert";
    public static final String CIVILIZATION_DESERT_RED = "civilization_desert_red";
    public static final String CIVILIZATION_TROPICAL = "civilization_tropical";
    public static final String CIVILIZATION_SNOW = "civilization_snow";
    public static final String CIVILIZATION_SPECIAL_AUTUMNAL = "civilization_special_autumnal";
    public static final String CIVILIZATION_SPECIAL_COASTAL = "civilization_special_coastal";
	public static final String CIVILIZATION_SPECIAL_FLOWERY = "civilization_special_flowery";
    public static final String CIVILIZATION_SPECIAL_ORIENTAL = "civilization_special_oriental";
    public static final String WILDERNESS_TEMPERATE = "wilderness_temperate";
    public static final String WILDERNESS_FIELDS = "wilderness_fields";
    public static final String WILDERNESS_CONIFEROUS = "wilderness_coniferous";
    public static final String WILDERNESS_DECIDUOUS = "wilderness_deciduous";
    public static final String WILDERNESS_ARID = "wilderness_arid";
    public static final String WILDERNESS_DESERT = "wilderness_desert";
    public static final String WILDERNESS_DESERT_RED = "wilderness_desert_red";
    public static final String WILDERNESS_TROPICAL = "wilderness_tropical";
    public static final String WILDERNESS_SNOW = "wilderness_snow";
    public static final String WILDERNESS_SPECIAL_AUTUMNAL = "wilderness_special_autumnal";
    public static final String WILDERNESS_SPECIAL_COASTAL = "wilderness_special_coastal";
    public static final String WILDERNESS_SPECIAL_ORIENTAL = "wilderness_special_oriental";
    public static final String OCEAN_DEEP = "all_ocean_deep";
    public static final String OCEAN_SHALLOW = "all_ocean_shallow";
    public static final String OCEAN_FROZEN = "ocean_frozen";
    public static final String OCEAN_DEEP_FROZEN = "ocean_deep_frozen";
    public static final String OCEAN_NOT_FROZEN = "ocean_not_frozen";
    public static final String OCEAN_WARM = "ocean_warm";
    public static final String OCEAN_WARM_DEEP = "ocean_deep_lukewarm";
    public static final String OCEAN_RARE_SHALLOW = "ocean_rare_shallow";
    public static final String OCEAN_RARE_DEEP = "ocean_rare_deep";
    public static final String RIVER_OR_COAST_NOT_FROZEN = "rivers_or_coasts_not_frozen";
    public static final String RIVER_OR_COAST_FROZEN = "rivers_or_coasts_frozen";
    public static final String RIVER_FROZEN = "rivers_frozen";
    public static final String RIVER_NOT_FROZEN = "rivers_not_frozen";
    public static final String RIVER_TEMPERATE = "rivers_temperate";
    public static final String RIVER_WARM = "rivers_warm";
    public static final String SPECIAL_BARREN = "special_barren";
    public static final String SPECIAL_CRAGGY = "special_craggy";
    public static final String SPECIAL_ICY = "special_icy";
    public static final String SPECIAL_MAGICAL = "special_magical";
    public static final String SPECIAL_MEDITERRANEAN = "special_mediterranean";
    public static final String SPECIAL_MOUNTAINOUS_COLD = "special_mountainous_cold";
    public static final String SPECIAL_MOUNTAINOUS_HOT = "special_mountainous_hot";
    public static final String SPECIAL_RUINED = "special_ruined";
    public static final String SPECIAL_SHROOMY = "special_shroomy";
    public static final String SPECIAL_SPOOKY = "special_spooky";
    public static final String SPECIAL_SWAMPY = "special_swampy";
    public static final String SPECIAL_SWAMPY_WARM = "special_swampy_warm";
    public static final String UNDERGROUND_LAND = "all_underground_land";
	

	public static String getNamespace(String structureEntry) {
        return structureEntry.split(":")[0];
    }

    public static String getLocation(String structureEntry) {
        ArrayList<String> parts = new ArrayList<>(Arrays.asList(structureEntry.split("/")));
		return getNamespace(structureEntry) + ":" + String.join("/", parts.subList(2, parts.size()));
    }

    public static String calculateStructureDifficulty(String structureEntry) {
        ArrayList<String> parts = new ArrayList<>(Arrays.asList(structureEntry.split("/")));
		return getNamespace(structureEntry) + ":" + String.join("/", parts.subList(2, parts.size()));
    }

    public static String getPath(String structureEntry) {
        return structureEntry.split(":")[1];
    }

	public static final SortedSet<String> supportedModifierTypes = new TreeSet<>(Arrays.asList(
		"neoforge:add_features",
		"neoforge:add_spawns",
		"forge:add_spawns"
	));

	public static final SortedSet<String> defaultFlatStructures = new TreeSet<>(Arrays.asList(
		"archaeology_ruins:adoberuins",
		"archaeology_ruins:mudblacksmithruin",
		"archaeology_ruins:mudpotterruin",
		"archaeology_ruins:mudschoolruin",
		"archaeology_ruins:ocean_ruin",
		"archaeology_ruins:ruined_desert_pyramid",
		"archaeology_ruins:ruined_ocean_monument",
		"archaeology_ruins:ruinedjungletemple",
		"archaeology_ruins:small_ocean_ruin",
		"archaeology_ruins:smallmudruin",
		"archaeology_ruins:warm_ocean_ruin",
		"ars_additions:arcane_library",
		"ars_additions:nexus_tower",
		"ars_additions:ruined_portal",
		"ars_additions:ruined_portal_large",
		"ati_structures:ancient_temple",
		"ati_structures:ancient_vessel",
		"ati_structures:arachnid_dwelling",
		"ati_structures:ati_stoneworks",
		"ati_structures:castillo",
		"ati_structures:catalonian_castle",
		"ati_structures:dark_keep",
		"ati_structures:dark_tower",
		"ati_structures:deepslate_keep",
		"ati_structures:desert_outpost",
		"ati_structures:dojo",
		"ati_structures:fortified_temple",
		"ati_structures:gnome_hut",
		"ati_structures:granite_fort",
		"ati_structures:haunted_ruin",
		"ati_structures:herobrine_stronghold",
		"ati_structures:ice_tribe",
		"ati_structures:illager_homestead",
		"ati_structures:illager_tower",
		"ati_structures:jungle_grotto",
		"ati_structures:jungle_settlement",
		"ati_structures:lighthouse",
		"ati_structures:manor",
		"ati_structures:marble_chateau",
		"ati_structures:monastery_tower",
		"ati_structures:mosque",
		"ati_structures:mud_tower",
		"ati_structures:nomadic_camp",
		"ati_structures:old_fort",
		"ati_structures:old_home",
		"ati_structures:old_residence",
		"ati_structures:overgrown_outpost",
		"ati_structures:pufferfish_cave",
		"ati_structures:quarry",
		"ati_structures:rotten_log",
		"ati_structures:rotting_temple",
		"ati_structures:rotting_temple_underground",
		"ati_structures:ruined_castle",
		"ati_structures:sculk_deposit",
		"ati_structures:silverfish_nest",
		"ati_structures:sinking_temple",
		"ati_structures:small_keep",
		"ati_structures:spider_nest",
		"ati_structures:steam_house",
		"ati_structures:storage_house",
		"ati_structures:storage_shack",
		"ati_structures:stray_ruins",
		"ati_structures:tavern",
		"ati_structures:underground_monument",
		"ati_structures:underwater_dungeon",
		"ati_structures:villager_inn",
		"ati_structures:warden_monument",
		"ati_structures:wither_cavern",
		"ati_structures:wither_keep",
		"ati_structures:woodland_keep",
		"beautify:botanist_house_desert",
		"beautify:botanist_house_plains",
		"beautify:botanist_house_savanna",
		"beautify:botanist_house_snowy",
		"beautify:botanist_house_taiga",
		"betterarcheology:archeologist_camp_grassy",
		"betterarcheology:archeologist_camp_redsand",
		"betterarcheology:archeologist_camp_sand",
		"betterarcheology:buried_ruins_sand",
		"betterarcheology:catacombs",
		"betterarcheology:desert_obelisk",
		"betterarcheology:fossil_chicken",
		"betterarcheology:fossil_chicken_birch",
		"betterarcheology:fossil_creeper",
		"betterarcheology:fossil_jungle_0",
		"betterarcheology:fossil_jungle_1",
		"betterarcheology:fossil_sheep_0",
		"betterarcheology:fossil_wolf",
		"betterarcheology:light_temple",
		"betterarcheology:mesa_ruins",
		"betterarcheology:mott",
		"betterarcheology:ruins_sand",
		"betterarcheology:stonehenge_grassy",
		"betterarcheology:temple_jungle",
		"betterarcheology:tumulus_grassy",
		"betterarcheology:underwater_0",
		"betterarcheology:underwater_1",
		"betterarcheology:underwater_2",
		"betterarcheology:underwater_3",
		"betterarcheology:villager_grave",
		"born_in_chaos_v1:clown_caravan_plains",
		"born_in_chaos_v1:clown_caravan_savanna",
		"born_in_chaos_v1:clown_caravan_taiga",
		"born_in_chaos_v1:dark_tower_forest",
		"born_in_chaos_v1:dark_tower_plain",
		"born_in_chaos_v1:dark_tower_taiga",
		"born_in_chaos_v1:farm",
		"born_in_chaos_v1:firewell",
		"born_in_chaos_v1:grave_2003wise",
		"born_in_chaos_v1:grave_2_dling",
		"born_in_chaos_v1:grave_d_4rk_devil_x",
		"born_in_chaos_v1:grave_darktitan",
		"born_in_chaos_v1:grave_derivas",
		"born_in_chaos_v1:grave_euthymia",
		"born_in_chaos_v1:grave_feral",
		"born_in_chaos_v1:grave_fubuki_banzai",
		"born_in_chaos_v1:grave_memesus",
		"born_in_chaos_v1:grave_mike_and_rory",
		"born_in_chaos_v1:grave_nino_4416",
		"born_in_chaos_v1:grave_orion",
		"born_in_chaos_v1:grave_petasi",
		"born_in_chaos_v1:grave_plug",
		"born_in_chaos_v1:grave_rotborne",
		"born_in_chaos_v1:grave_somfunambulist",
		"born_in_chaos_v1:grave_tem_187",
		"born_in_chaos_v1:grave_the_gentleman_frog",
		"born_in_chaos_v1:gravecarrionexe",
		"born_in_chaos_v1:infernal_pumpkin",
		"born_in_chaos_v1:mound_of_hounds",
		"born_in_chaos_v1:observation_tower_forest",
		"born_in_chaos_v1:observation_tower_plains",
		"bosses_of_mass_destruction:gauntlet_arena",
		"bosses_of_mass_destruction:lich_tower",
		"bosses_of_mass_destruction:obsidilith_arena",
		"combat_structures_update:acacia_trader_boat",
		"combat_structures_update:acaciatreehouse",
		"combat_structures_update:badlandslostwell",
		"combat_structures_update:basaltobsidianspike",
		"combat_structures_update:beach_house",
		"combat_structures_update:birch_cottage",
		"combat_structures_update:blackstonenetherportal_1",
		"combat_structures_update:bunker",
		"combat_structures_update:dark_oak_illager_ship",
		"combat_structures_update:end_islandhanging_fortress",
		"combat_structures_update:end_ruin",
		"combat_structures_update:flyingboat",
		"combat_structures_update:glowsroomobsidianspike",
		"combat_structures_update:hugemangrovetreehut",
		"combat_structures_update:icespike_ruin",
		"combat_structures_update:illagerwarship",
		"combat_structures_update:jungle_illager_ship",
		"combat_structures_update:large_obsidian_spike",
		"combat_structures_update:mangrove_canoe",
		"combat_structures_update:mansion",
		"combat_structures_update:nether_basalt_portal",
		"combat_structures_update:nether_brute_room",
		"combat_structures_update:nether_hoglin_homestead",
		"combat_structures_update:nether_mine_shafts",
		"combat_structures_update:nether_obsidian_spike_1",
		"combat_structures_update:nether_skeleton",
		"combat_structures_update:nether_small_gold_fort",
		"combat_structures_update:nether_strider_dock",
		"combat_structures_update:nethercastle",
		"combat_structures_update:netherlargewarpedtree_1",
		"combat_structures_update:netherlargewarpedtree_2",
		"combat_structures_update:netherlargewarpedtree_3",
		"combat_structures_update:netherlargewarpedtree_4",
		"combat_structures_update:netherlargewarpedtreehouse",
		"combat_structures_update:netherlongspike",
		"combat_structures_update:netherrack_mine_tunnels",
		"combat_structures_update:netherrackspike",
		"combat_structures_update:oak_villager_paddlewheel_boat",
		"combat_structures_update:oak_villager_ship",
		"combat_structures_update:obsidian_end_castle",
		"combat_structures_update:obsidian_spike_feature_2",
		"combat_structures_update:obsidian_spike_feature_3",
		"combat_structures_update:obsidian_spike_feature_4",
		"combat_structures_update:obsidian_spike_feature_5",
		"combat_structures_update:obsidianlootspike",
		"combat_structures_update:obsidianspikefeature_1",
		"combat_structures_update:obsidianspikespreading",
		"combat_structures_update:ocean_glass_dome",
		"combat_structures_update:overworld_obsidianspike_2",
		"combat_structures_update:overworldobsidianspike_1",
		"combat_structures_update:overworldobsidianspike_3",
		"combat_structures_update:pillager_village",
		"combat_structures_update:purple_castle",
		"combat_structures_update:ravagerpen",
		"combat_structures_update:ruined_end_city",
		"combat_structures_update:ruinedendship",
		"combat_structures_update:ruinedoceantower",
		"combat_structures_update:ruinedpurpleroom",
		"combat_structures_update:ruinedstonyportal",
		"combat_structures_update:ruinedstronghold",
		"combat_structures_update:runieddesertportal",
		"combat_structures_update:shulker_end_city",
		"combat_structures_update:small_obsidian_spike",
		"combat_structures_update:smallendislandbridge_1",
		"combat_structures_update:smallendislandbridge_2",
		"combat_structures_update:smallendislandbridge_3",
		"combat_structures_update:smallendislandhouse_1",
		"combat_structures_update:smallendislandhouse_2",
		"combat_structures_update:smallendislandruin_1",
		"combat_structures_update:smallendislandruin_2",
		"combat_structures_update:smallendislandruin_3",
		"combat_structures_update:smallendislandruin_4",
		"combat_structures_update:smallendislandruin_5",
		"combat_structures_update:sprucevillagership",
		"combat_structures_update:stone_library_catacombs",
		"combat_structures_update:tainted_crossroads",
		"combat_structures_update:taintedicespike",
		"combat_structures_update:taintedobsidianhouse",
		"combat_structures_update:taintedobsidianonland",
		"combat_structures_update:towerruin",
		"combat_structures_update:tudor_castle",
		"combat_structures_update:turdor_watchtower",
		"combat_structures_update:watercastle",
		"combat_structures_update:wither_castle",
		"create_ltab:birch_structures",
		"create_ltab:cave_ruins",
		"create_ltab:cherry_house",
		"create_ltab:dark_forest_house",
		"create_ltab:grot",
		"create_ltab:jungle_well",
		"create_ltab:mangrove_structures",
		"create_ltab:nether_roof_house",
		"create_ltab:pillage",
		"create_ltab:plains_big",
		"create_ltab:plains_small",
		"create_ltab:quarry",
		"create_ltab:ruins",
		"create_ltab:sand_house",
		"create_ltab:snow_fort",
		"create_ltab:spruce_structures",
		"create_ltab:the_caretakersbunker",
		"create_ltab:thecastle",
		"create_ltab:water_pre",
		"create_pillagers_arise:cathedral_create",
		"create_pillagers_arise:createchinatower",
		"create_pillagers_arise:createpillagerblimp",
		"create_pillagers_arise:createpillagercamp",
		"create_pillagers_arise:createpillagerfortgate",
		"create_pillagers_arise:createpillagerhousesmall",
		"create_pillagers_arise:createpillageroutpost",
		"create_pillagers_arise:createpillagersmallhouse",
		"create_pillagers_arise:createpillagervillage",
		"create_pillagers_arise:pillagercreatetower",
		"create_rustic_structures:rustic_barn",
		"create_rustic_structures:rustic_smithy",
		"create_rustic_structures:rustic_well",
		"create_rustic_structures:rustic_windmill",
		"create_structures_arise:create_copper_statue",
		"create_structures_arise:create_dungeon_base",
		"create_structures_arise:create_ruined_castle",
		"create_structures_arise:createairdrop",
		"create_structures_arise:createcontainer",
		"create_structures_arise:createcushercrane",
		"create_structures_arise:createfluidtank",
		"create_structures_arise:createhouse",
		"create_structures_arise:createlittleman",
		"create_structures_arise:createlosttrainstation",
		"create_structures_arise:createminiskyvillage",
		"create_structures_arise:createoldruine",
		"create_structures_arise:createpickaxestatue",
		"create_structures_arise:darkcastle",
		"create_structures_arise:deadlordshouse",
		"create_structures_arise:minetrain",
		"create_structures_arise:obsidiantemple",
		"create_structures_arise:pillager_boat",
		"create_structures_arise:pillagersteampunkairship",
		"create_structures_arise:windmill",
		"darkerdepths:catacombs",
		"darkerdepths:rope_mine_desert",
		"darkerdepths:rope_mine_forest",
		"dungeons_arise:abandoned_temple",
		"dungeons_arise:aviary",
		"dungeons_arise:bandit_towers",
		"dungeons_arise:bandit_village",
		"dungeons_arise:bathhouse",
		"dungeons_arise:ceryneian_hind",
		"dungeons_arise:coliseum",
		"dungeons_arise:fishing_hut",
		"dungeons_arise:foundry",
		"dungeons_arise:giant_mushroom",
		"dungeons_arise:greenwood_pub",
		"dungeons_arise:heavenly_challenger",
		"dungeons_arise:heavenly_conqueror",
		"dungeons_arise:heavenly_rider",
		"dungeons_arise:illager_campsite",
		"dungeons_arise:illager_corsair",
		"dungeons_arise:illager_fort",
		"dungeons_arise:illager_galley",
		"dungeons_arise:illager_windmill",
		"dungeons_arise:infested_temple",
		"dungeons_arise:jungle_tree_house",
		"dungeons_arise:keep_kayra",
		"dungeons_arise:kisegi_sanctuary",
		"dungeons_arise:lighthouse",
		"dungeons_arise:mechanical_nest",
		"dungeons_arise:merchant_campsite",
		"dungeons_arise:mining_complex",
		"dungeons_arise:mining_system",
		"dungeons_arise:monastery",
		"dungeons_arise:mushroom_house",
		"dungeons_arise:mushroom_mines",
		"dungeons_arise:mushroom_village",
		"dungeons_arise:plague_asylum",
		"dungeons_arise:scorched_mines",
		"dungeons_arise:shiraz_palace",
		"dungeons_arise:small_blimp",
		"dungeons_arise:thornborn_towers",
		"dungeons_arise:typhon",
		"dungeons_arise:undead_pirate_ship",
		"dungeons_arise:wishing_well",
		"dungeons_arise_seven_seas:corsair_corvette",
		"dungeons_arise_seven_seas:pirate_junk",
		"dungeons_arise_seven_seas:small_yacht",
		"dungeons_arise_seven_seas:unicorn_galleon",
		"dungeons_arise_seven_seas:victory_frigate",
		"endersdelight:end_house",
		"epic:witch_hut",
		"explorify:badlands_pyramid",
		"explorify:black_spiral",
		"explorify:campsite",
		"explorify:dark_forest_settlement",
		"explorify:desert_shrine",
		"explorify:end_shipwreck",
		"explorify:farmstead",
		"explorify:guide_post_cold",
		"explorify:guide_post_warm",
		"explorify:mangrove_hut",
		"explorify:mausoleum",
		"explorify:ruins",
		"explorify:supply_cache/birch",
		"explorify:supply_cache/dark",
		"explorify:supply_cache/desert",
		"explorify:supply_cache/forest",
		"explorify:supply_cache/jungle",
		"explorify:supply_cache/mangrove",
		"explorify:supply_cache/taiga",
		"explorify:tavern",
		"explorify:watchtower/plains",
		"explorify:watchtower/savanna",
		"explorify:watchtower/taiga",
		"farmers_structures:aether",
		"farmers_structures:afterdark_farms",
		"farmers_structures:aquacultures_beach",
		"farmers_structures:aquacultures_cod",
		"farmers_structures:aquacultures_common",
		"farmers_structures:cacaos",
		"farmers_structures:cooks",
		"farmers_structures:cooks_moss",
		"farmers_structures:cooks_nether_1",
		"farmers_structures:cooks_nether_2",
		"farmers_structures:deeper_farms",
		"farmers_structures:fishs_stew",
		"farmers_structures:flesh_farms",
		"farmers_structures:honey_cake_farms",
		"farmers_structures:ratatouilles",
		"farmers_structures:shepherd_farms",
		"farmers_structures:squids",
		"farmers_structures:sushis",
		"farmers_structures:undergardens",
		"farmers_structures:undergardens_sea",
		"feur_extension_desert:anubis_arena",
		"feur_extension_desert:anubis_road",
		"feur_extension_desert:anubis_statue",
		"feur_extension_desert:arena_oasis",
		"feur_extension_desert:cactus_1",
		"feur_extension_desert:cactus_2",
		"feur_extension_desert:cactus_3",
		"feur_extension_desert:cactus_4",
		"feur_extension_desert:cactus_5",
		"feur_extension_desert:cactus_6",
		"feur_extension_desert:cactus_7",
		"feur_extension_desert:cactus_arc_1",
		"feur_extension_desert:cactus_arc_2",
		"feur_extension_desert:cactus_big",
		"feur_extension_desert:oasis_big",
		"feur_extension_desert:oasis_small",
		"feur_extension_desert:old_house",
		"feur_extension_desert:old_tower",
		"feur_extension_desert:old_village",
		"feur_extension_desert:pyramid",
		"feur_extension_desert:redrock",
		"feur_extension_desert:rock",
		"feur_extension_desert:sphynx",
		"feur_extension_fossil:bones_tree",
		"feur_extension_fossil:fossil_arc",
		"feur_extension_fossil:fossil_baby_fish",
		"feur_extension_fossil:fossil_bone_fish",
		"feur_extension_fossil:fossil_chest",
		"feur_extension_fossil:fossil_dragon",
		"feur_extension_fossil:fossil_fang",
		"feur_extension_fossil:fossil_fish",
		"feur_extension_fossil:fossil_guardian",
		"feur_extension_fossil:fossil_hand",
		"feur_extension_fossil:fossil_snake",
		"feur_extension_fossil:rex_camp",
		"feur_extension_fossil:skull_camp",
		"feur_extension_fossil:small_coal_rex_camp",
		"feur_extension_fossil:small_rex_camp",
		"feur_extension_jungle:ancient_statue",
		"feur_extension_jungle:big_melon",
		"feur_extension_jungle:fountain",
		"feur_extension_jungle:lost_explorer",
		"feur_extension_jungle:old_house",
		"feur_extension_jungle:protector",
		"feur_extension_jungle:pyramid",
		"feur_extension_jungle:small_temple",
		"feur_extension_jungle:tree_ancestral",
		"feur_extension_jungle:tree_ancestral_house",
		"feur_extension_jungle:tree_stump",
		"hopo:mineshaft/acacia_mineshaft",
		"hopo:mineshaft/bamboo_mineshaft",
		"hopo:mineshaft/biomes/dripstone_mineshaft",
		"hopo:mineshaft/biomes/lush_mineshaft",
		"hopo:mineshaft/birch_mineshaft",
		"hopo:mineshaft/cherry_mineshaft",
		"hopo:mineshaft/dark_oak_mineshaft",
		"hopo:mineshaft/deepslate_mineshaft",
		"hopo:mineshaft/jungle_mineshaft",
		"hopo:mineshaft/mangrove_mineshaft",
		"hopo:mineshaft/mud_mineshaft",
		"hopo:mineshaft/oak_mineshaft",
		"hopo:mineshaft/spruce_mineshaft",
		"hopo:mineshaft/stone_mineshaft",
		"hopo:portal/nether/piglin_ruin",
		"hopo:portal/overworld/portal_deepslate",
		"hopo:portal/overworld/portal_dripstone",
		"hopo:portal/overworld/portal_lush",
		"hopo:portal/overworld/portal_ruined",
		"hopo:underwater/underwater_city",
		"hopo:underwater/underwater_fossils",
		"hopo:underwater/underwater_small_ruins",
		"hopo:underwater/underwater_warm_small_ruins",
		"imst:airship",
		"imst:alpine_house",
		"imst:balloon",
		"imst:bandit_camp",
		"imst:beehouse",
		"imst:berry_house",
		"imst:cactus_farm",
		"imst:caravan",
		"imst:cocoa_farm",
		"imst:dark_tower",
		"imst:desert_well",
		"imst:el_dorado",
		"imst:flowerdome",
		"imst:fossil_swamp",
		"imst:igloo",
		"imst:lumberjack/acacia_hut",
		"imst:lumberjack/birch_hut",
		"imst:lumberjack/dark_oak_hut",
		"imst:lumberjack/jungle_hut",
		"imst:lumberjack/mangrove_hut",
		"imst:lumberjack/oak_hut",
		"imst:lumberjack/spruce_hut",
		"imst:mountain_camp",
		"imst:observatory",
		"imst:pyramid",
		"imst:quarry",
		"imst:sunflower_farm",
		"imst:terralith/yurt",
		"imst:train_station",
		"imst:viking_house",
		"imst:witch_hut",
		"medieval_buildings:fort",
		"medieval_buildings:house_1",
		"medieval_buildings:house_2",
		"medieval_buildings:ship",
		"medieval_buildings:tower",
		"minecraft:ancient_city",
		"minecraft:bastion_remnant",
		"minecraft:pillager_outpost",
		"minecraft:pillager_outpost_dark_forest",
		"minecraft:pillager_outpost_forest",
		"minecraft:pillager_outpost_mangrove",
		"minecraft:pillager_outpost_swamp",
		"minecraft:stronghold_big",
		"minecraft:trail_ruins",
		"minecraft:trial_chambers",
		"minecraft:village_desert",
		"minecraft:village_plains",
		"minecraft:village_savanna",
		"minecraft:village_snowy",
		"minecraft:village_taiga",
		"mostructures:air_balloon",
		"mostructures:barn_house",
		"mostructures:big_pyramid",
		"mostructures:desert_abandoned_church",
		"mostructures:ice_tower",
		"mostructures:jungle_pyramid",
		"mostructures:killer_bunny_castle",
		"mostructures:lighthouse",
		"mostructures:moai",
		"mostructures:pillager_factory",
		"mostructures:pillager_mines",
		"mostructures:pirate_ship",
		"mostructures:plains_abandoned_church",
		"mostructures:savanna_abandoned_church",
		"mostructures:snowy_abandoned_church",
		"mostructures:sphinx",
		"mostructures:taiga_abandoned_church",
		"mostructures:tavern",
		"mostructures:the_castle_in_the_sky",
		"mostructures:villager_market",
		"mostructures:villager_tower",
		"mss:arena",
		"mss:birch_river",
		"mss:calcite_house",
		"mss:castle_ruin",
		"mss:castle_tower",
		"mss:cherry_river",
		"mss:desert_pyramid",
		"mss:desert_well",
		"mss:diorite_house",
		"mss:frozen_pond",
		"mss:jungle",
		"mss:large_tower",
		"mss:leaf_hollow",
		"mss:mangrove",
		"mss:muddy_water_hole",
		"mss:mushroom",
		"mss:nether_portal",
		"mss:palm_island",
		"mss:red_sand",
		"mss:small_deepslate_house",
		"mss:small_oak_house",
		"mss:small_pond",
		"mss:small_tower",
		"mss:spruce_huts",
		"mss:taiga",
		"mss:tree_1",
		"mss:tree_2",
		"mss:tree_3",
		"mss:tree_4",
		"mss:tree_5",
		"mss:tree_6",
		"mss:tree_7",
		"mss:tree_8",
		"mss:volcano",
		"mss:white_house",
		"mtr:desert_temple",
		"mtr:jungle_temple",
		"mtr:ocean_temple",
		"mtr:stronghold",
		"mushroomquest:witch_cottage_redone",
		"mvs:acacia_log_pile",
		"mvs:acacia_tree",
		"mvs:acacia_well",
		"mvs:azelea_house",
		"mvs:barn",
		"mvs:beach_bar",
		"mvs:bee_dome",
		"mvs:bench",
		"mvs:big_oak_tree",
		"mvs:birch_log_pile",
		"mvs:birch_tree",
		"mvs:birch_well",
		"mvs:blue_stall",
		"mvs:boulder",
		"mvs:campsite",
		"mvs:cart",
		"mvs:cartographer_tower",
		"mvs:castle_ruins",
		"mvs:cathedral",
		"mvs:cherry_tree",
		"mvs:crystal",
		"mvs:dark_oak_log_pile",
		"mvs:dark_oak_tree",
		"mvs:dark_oak_well",
		"mvs:dead_tree_acacia",
		"mvs:dead_tree_birch",
		"mvs:dead_tree_cherry",
		"mvs:dead_tree_dark_oak",
		"mvs:dead_tree_jungle",
		"mvs:dead_tree_mangrove",
		"mvs:dead_tree_oak",
		"mvs:dead_tree_spruce",
		"mvs:deepslate_house",
		"mvs:desert_house",
		"mvs:desert_pump",
		"mvs:desert_well",
		"mvs:duck",
		"mvs:end_scraps_1",
		"mvs:end_scraps_2",
		"mvs:end_scraps_3",
		"mvs:end_scraps_4",
		"mvs:end_well",
		"mvs:fire_camp",
		"mvs:floating_islands",
		"mvs:flower_hole",
		"mvs:fox_hut",
		"mvs:gallows",
		"mvs:haystack",
		"mvs:horse_campsite",
		"mvs:horse_pen",
		"mvs:house",
		"mvs:jungle_log_pile",
		"mvs:jungle_palm_tree",
		"mvs:jungle_tower",
		"mvs:jungle_tree",
		"mvs:jungle_well",
		"mvs:lamp_chest",
		"mvs:large_cart_1",
		"mvs:large_cart_2",
		"mvs:large_floating_island",
		"mvs:large_mushroom",
		"mvs:large_warped_tower",
		"mvs:lecturn_garden",
		"mvs:log_ruin",
		"mvs:medium_bamboo_cart",
		"mvs:medium_igloo_1",
		"mvs:medium_oak_lantern",
		"mvs:mine_with_campsite",
		"mvs:mineshaft",
		"mvs:mushroom_pond",
		"mvs:mushroom_statue",
		"mvs:mushroom_well",
		"mvs:oak_log_pile",
		"mvs:oak_tree",
		"mvs:oak_well",
		"mvs:ocean_tower",
		"mvs:orange_stall",
		"mvs:out_house",
		"mvs:paths",
		"mvs:pile",
		"mvs:pink_stall",
		"mvs:railway",
		"mvs:rare_well",
		"mvs:red_stall",
		"mvs:red_tower",
		"mvs:rocky_well",
		"mvs:ruined_beacon",
		"mvs:shed",
		"mvs:small_acacia_lantern",
		"mvs:small_bamboo_lantern",
		"mvs:small_birch_lantern",
		"mvs:small_campfire_lantern",
		"mvs:small_cherry_lantern",
		"mvs:small_copper_well",
		"mvs:small_dark_oak_lantern",
		"mvs:small_igloo",
		"mvs:small_jungle_lantern",
		"mvs:small_mangrove_lantern",
		"mvs:small_oak_lantern",
		"mvs:small_oak_pond",
		"mvs:small_pillager_tower",
		"mvs:small_ruin",
		"mvs:small_ship",
		"mvs:small_spruce_lantern",
		"mvs:small_swamp_house",
		"mvs:small_tower_well",
		"mvs:small_well",
		"mvs:snowy_dog_hut",
		"mvs:snowy_fossil",
		"mvs:snowy_well",
		"mvs:spruce_log_pile",
		"mvs:spruce_tree",
		"mvs:spruce_well",
		"mvs:statue_ruins",
		"mvs:stone_fountain",
		"mvs:stone_pillars",
		"mvs:stone_rock",
		"mvs:sunzi_gate",
		"mvs:tall_house",
		"mvs:tree_monument",
		"mvs:villager_statue",
		"mvs:warped_house",
		"mvs:well",
		"mvs:wheat_grain_bin",
		"mvs:windmill",
		"mvs:wooden_wheat_farm",
		"mythsandlegends:ancient_vestiges",
		"mythsandlegends:graveyard",
		"mythsandlegends:old_camp",
		"mythsandlegends:scorched_nest",
		"mythsandlegends:sepulcrum_ignitum",
		"natures_spirit:village_adobe",
		"natures_spirit:village_coconut",
		"natures_spirit:village_cypress",
		"natures_spirit:village_wisteria",
		"nordic_structures:bigvikingeatinghouse",
		"nordic_structures:dwarfcavern_1",
		"nordic_structures:largevikingvillage",
		"nordic_structures:specialvikinglongboat_1",
		"nordic_structures:specialvikinglongboat_2",
		"nordic_structures:tyrfingrshrine",
		"nordic_structures:vikingfarm",
		"nordic_structures:vikingfort",
		"nordic_structures:vikinglongboatboss",
		"nordic_structures:vikingstatue",
		"nordic_structures:vikingstatuebirch",
		"nordic_structures:vikingstatueplains",
		"nordic_structures:vikingtent",
		"nordic_structures:vikingtower",
		"nova_structures:badlands_miner_outpost",
		"nova_structures:bunker",
		"nova_structures:conduit_ruin",
		"nova_structures:creeping_crypt",
		"nova_structures:deepslate_camp",
		"nova_structures:desert_ruins",
		"nova_structures:end_castle",
		"nova_structures:end_lighthouse",
		"nova_structures:end_ship",
		"nova_structures:firewatch_tower_birch",
		"nova_structures:firewatch_tower_cherry",
		"nova_structures:firewatch_tower_dark_oak",
		"nova_structures:firewatch_tower_forest",
		"nova_structures:firewatch_tower_jungle",
		"nova_structures:firewatch_tower_mangrove",
		"nova_structures:firewatch_tower_savanna",
		"nova_structures:firewatch_tower_swamp",
		"nova_structures:firewatch_tower_taiga",
		"nova_structures:hamlet",
		"nova_structures:illager_camp",
		"nova_structures:illager_hideout",
		"nova_structures:illager_manor",
		"nova_structures:jungle_ruins",
		"nova_structures:lone_citadel",
		"nova_structures:mangrove_witch_hut",
		"nova_structures:nether_keep",
		"nova_structures:nether_port",
		"nova_structures:nether_skeleton_tower_crimson",
		"nova_structures:nether_skeleton_tower_soul",
		"nova_structures:nether_skeleton_tower_warped",
		"nova_structures:nether_skeleton_tower_waste",
		"nova_structures:piglin_camp",
		"nova_structures:piglin_donjon",
		"nova_structures:piglin_outstation",
		"nova_structures:remnant_bee_keeper",
		"nova_structures:remnant_big_remnant",
		"nova_structures:remnant_big_remnant_2",
		"nova_structures:remnant_big_remnant_3",
		"nova_structures:remnant_birch_graveyard",
		"nova_structures:remnant_bridge_remnant",
		"nova_structures:remnant_bunny_base",
		"nova_structures:remnant_classic_village",
		"nova_structures:remnant_desert_remnant",
		"nova_structures:remnant_forest_smith",
		"nova_structures:remnant_frog_ranch",
		"nova_structures:remnant_graveyard",
		"nova_structures:remnant_medium_remnant",
		"nova_structures:remnant_medium_remnant_2",
		"nova_structures:remnant_miner_hut",
		"nova_structures:remnant_mud_brick_constructor",
		"nova_structures:remnant_ominous_shop",
		"nova_structures:remnant_ruin_farmer",
		"nova_structures:remnant_ruin_smith",
		"nova_structures:remnant_sawmill",
		"nova_structures:remnant_school_remnant",
		"nova_structures:remnant_taiga_castle",
		"nova_structures:remnant_woodland_hud",
		"nova_structures:remnant_zombie_horse_ranch",
		"nova_structures:ruin_town",
		"nova_structures:shrine_combat_tier_1",
		"nova_structures:shrine_combat_tier_2",
		"nova_structures:shrine_combat_tier_3",
		"nova_structures:shrine_combat_tier_4",
		"nova_structures:shrine_combat_tier_5",
		"nova_structures:shrine_tower",
		"nova_structures:skeleton_camp_crimson",
		"nova_structures:skeleton_camp_soul",
		"nova_structures:skeleton_camp_warped",
		"nova_structures:skeleton_camp_waste",
		"nova_structures:stray_fort",
		"nova_structures:tavern_acacia",
		"nova_structures:tavern_birch",
		"nova_structures:tavern_cherry",
		"nova_structures:tavern_dark_oak",
		"nova_structures:tavern_desert",
		"nova_structures:tavern_jungle",
		"nova_structures:tavern_mangrove",
		"nova_structures:tavern_oak",
		"nova_structures:tavern_snowy",
		"nova_structures:tavern_spruce",
		"nova_structures:tavern_swamp",
		"nova_structures:toxic_lair",
		"nova_structures:trident_trial_monument",
		"nova_structures:undead_crypt",
		"nova_structures:underground_house",
		"nova_structures:village_birch",
		"nova_structures:village_jungle",
		"nova_structures:village_swamp",
		"nova_structures:well_birch",
		"nova_structures:well_dark_oak",
		"nova_structures:well_jungle",
		"nova_structures:well_oak",
		"nova_structures:well_savana",
		"nova_structures:well_spruce",
		"nova_structures:wild_ruin",
		"nova_structures:witch_villa",
		"nullscape:dragon_skeleton",
		"nullscape:rift",
		"philipsruins:ancient_crypt",
		"philipsruins:ancient_dungeon",
		"philipsruins:ancient_ruins",
		"philipsruins:ancient_towers",
		"philipsruins:field_stone_ruins",
		"philipsruins:field_stone_ruins_rocks",
		"philipsruins:level_one_ruins",
		"philipsruins:level_three_ruins",
		"philipsruins:level_two_ruins",
		"philipsruins:level_two_ruins_pool",
		"philipsruins:lost_soul_city",
		"philipsruins:lost_soul_dungeon",
		"philipsruins:ocean_fortress",
		"philipsruins:ocean_ruins",
		"philipsruins:pumpkin_ruins",
		"philipsruins:rare_ruin",
		"philipsruins:underground_structures",
		"repurposed_structures:ancient_city_end",
		"repurposed_structures:ancient_city_nether",
		"repurposed_structures:ancient_city_ocean",
		"repurposed_structures:bastion_underground",
		"repurposed_structures:city_overworld",
		"repurposed_structures:fortress_jungle",
		"repurposed_structures:igloo_grassy",
		"repurposed_structures:igloo_mangrove",
		"repurposed_structures:igloo_mushroom",
		"repurposed_structures:igloo_stone",
		"repurposed_structures:mineshaft_basalt",
		"repurposed_structures:mineshaft_crimson",
		"repurposed_structures:mineshaft_nether",
		"repurposed_structures:mineshaft_soul",
		"repurposed_structures:mineshaft_warped",
		"repurposed_structures:outpost_badlands",
		"repurposed_structures:outpost_birch",
		"repurposed_structures:outpost_desert",
		"repurposed_structures:outpost_end",
		"repurposed_structures:outpost_giant_tree_taiga",
		"repurposed_structures:outpost_icy",
		"repurposed_structures:outpost_jungle",
		"repurposed_structures:outpost_mangrove",
		"repurposed_structures:outpost_oak",
		"repurposed_structures:outpost_ocean",
		"repurposed_structures:outpost_savanna",
		"repurposed_structures:outpost_snowy",
		"repurposed_structures:outpost_taiga",
		"repurposed_structures:pyramid_badlands",
		"repurposed_structures:pyramid_dark_forest",
		"repurposed_structures:pyramid_end",
		"repurposed_structures:pyramid_flower_forest",
		"repurposed_structures:pyramid_giant_tree_taiga",
		"repurposed_structures:pyramid_icy",
		"repurposed_structures:pyramid_jungle",
		"repurposed_structures:pyramid_mushroom",
		"repurposed_structures:pyramid_ocean",
		"repurposed_structures:pyramid_snowy",
		"repurposed_structures:ruined_portal_end",
		"repurposed_structures:ruins_land_cold",
		"repurposed_structures:ruins_land_hot",
		"repurposed_structures:ruins_land_icy",
		"repurposed_structures:ruins_land_warm",
		"repurposed_structures:shipwreck_end",
		"repurposed_structures:stronghold_nether",
		"repurposed_structures:temple_ocean",
		"repurposed_structures:temple_taiga",
		"repurposed_structures:village_badlands",
		"repurposed_structures:village_bamboo",
		"repurposed_structures:village_birch",
		"repurposed_structures:village_cherry",
		"repurposed_structures:village_dark_forest",
		"repurposed_structures:village_giant_taiga",
		"repurposed_structures:village_jungle",
		"repurposed_structures:village_mountains",
		"repurposed_structures:village_mushroom",
		"repurposed_structures:village_oak",
		"repurposed_structures:village_ocean",
		"repurposed_structures:village_swamp",
		"repurposed_structures:witch_hut_birch",
		"repurposed_structures:witch_hut_dark_forest",
		"repurposed_structures:witch_hut_giant_tree_taiga",
		"repurposed_structures:witch_hut_mangrove",
		"repurposed_structures:witch_hut_oak",
		"repurposed_structures:witch_hut_taiga",
		"sky_whale_ship:frozen_whale",
		"sky_whale_ship:whale",
		"sky_whale_ship:whalearena",
		"sky_whale_ship:whalelight",
		"sky_whale_ship:whaleship",
		"skyarena:ice_arena",
		"skyarena:sky_arena",
		"skyvillages:skyvillage",
		"structory:abandoned_camp",
		"structory:abandoned_chapel",
		"structory:boat",
		"structory:dense_forest_ruin",
		"structory:firetower",
		"structory:graveyard",
		"structory:jungle_ruin",
		"structory:northern_ruin",
		"structory:old_manor",
		"structory:outcast_villager_desert",
		"structory:outcast_villager_grassy",
		"structory:ruin_grassy",
		"structory:swamp_ruin",
		"structory:taiga_ruin_surface",
		"structory:taiga_ruin_underground",
		"structory_towers:ancient_temple",
		"structory_towers:end/end_tower",
		"structory_towers:engineer_tower",
		"structory_towers:farmer_outpost",
		"structory_towers:foraging_outpost",
		"structory_towers:great_toadstool",
		"structory_towers:lighthouse",
		"structory_towers:mirage_outpost",
		"structory_towers:nether/fortress_tower",
		"structory_towers:nether/strange_outpost",
		"structory_towers:nether/warped_outpost",
		"structory_towers:nomad_outpost",
		"structory_towers:ocean_pillar",
		"structory_towers:overgrown_mangrove",
		"structory_towers:pillager_lookout",
		"structory_towers:quarter_outpost",
		"structory_towers:sacred_relic_temple",
		"structory_towers:small_firetower",
		"structory_towers:taiga_outpost",
		"structory_towers:warped_greatsword",
		"structory_towers:wizard_tower",
		"totw_modded:aether",
		"totw_modded:badlands",
		"totw_modded:derelict",
		"totw_modded:derelict_grass",
		"totw_modded:desert",
		"totw_modded:end",
		"totw_modded:everbright",
		"totw_modded:everdawn",
		"totw_modded:glacio",
		"totw_modded:ice",
		"totw_modded:jungle",
		"totw_modded:mars",
		"totw_modded:mercury",
		"totw_modded:moon",
		"totw_modded:nether",
		"totw_modded:ocean",
		"totw_modded:ocean_warm",
		"totw_modded:ratlantis",
		"totw_modded:regular",
		"totw_modded:tw_canopy",
		"totw_modded:tw_mangrove",
		"totw_modded:venus",
		"towns_and_towers:exclusives/pillager_outpost_classic",
		"towns_and_towers:exclusives/pillager_outpost_iberian",
		"towns_and_towers:exclusives/pillager_outpost_mediterranean",
		"towns_and_towers:exclusives/pillager_outpost_nilotic",
		"towns_and_towers:exclusives/pillager_outpost_oriental",
		"towns_and_towers:exclusives/pillager_outpost_rustic",
		"towns_and_towers:exclusives/pillager_outpost_swedish",
		"towns_and_towers:exclusives/pillager_outpost_tudor",
		"towns_and_towers:exclusives/village_classic",
		"towns_and_towers:exclusives/village_iberian",
		"towns_and_towers:exclusives/village_mediterranean",
		"towns_and_towers:exclusives/village_nilotic",
		"towns_and_towers:exclusives/village_piglin",
		"towns_and_towers:exclusives/village_rustic",
		"towns_and_towers:exclusives/village_swedish",
		"towns_and_towers:exclusives/village_tudor",
		"towns_and_towers:exclusives/village_wandering_trader_camp",
		"towns_and_towers:mimic_desert",
		"towns_and_towers:pillager_outpost_badlands",
		"towns_and_towers:pillager_outpost_beach",
		"towns_and_towers:pillager_outpost_birch_forest",
		"towns_and_towers:pillager_outpost_desert",
		"towns_and_towers:pillager_outpost_flower_forest",
		"towns_and_towers:pillager_outpost_forest",
		"towns_and_towers:pillager_outpost_grove",
		"towns_and_towers:pillager_outpost_jungle",
		"towns_and_towers:pillager_outpost_meadow",
		"towns_and_towers:pillager_outpost_mushroom_fields",
		"towns_and_towers:pillager_outpost_ocean",
		"towns_and_towers:pillager_outpost_old_growth_taiga",
		"towns_and_towers:pillager_outpost_savanna",
		"towns_and_towers:pillager_outpost_savanna_plateau",
		"towns_and_towers:pillager_outpost_snowy_beach",
		"towns_and_towers:pillager_outpost_snowy_plains",
		"towns_and_towers:pillager_outpost_snowy_slopes",
		"towns_and_towers:pillager_outpost_snowy_taiga",
		"towns_and_towers:pillager_outpost_sparse_jungle",
		"towns_and_towers:pillager_outpost_sunflower_plains",
		"towns_and_towers:pillager_outpost_swamp",
		"towns_and_towers:pillager_outpost_taiga",
		"towns_and_towers:pillager_outpost_wooded_badlands",
		"towns_and_towers:village_badlands",
		"towns_and_towers:village_beach",
		"towns_and_towers:village_birch_forest",
		"towns_and_towers:village_flower_forest",
		"towns_and_towers:village_forest",
		"towns_and_towers:village_grove",
		"towns_and_towers:village_jungle",
		"towns_and_towers:village_meadow",
		"towns_and_towers:village_mushroom_fields",
		"towns_and_towers:village_ocean",
		"towns_and_towers:village_old_growth_taiga",
		"towns_and_towers:village_savanna_plateau",
		"towns_and_towers:village_snowy_slopes",
		"towns_and_towers:village_snowy_taiga",
		"towns_and_towers:village_sparse_jungle",
		"towns_and_towers:village_sunflower_plains",
		"towns_and_towers:village_swamp",
		"towns_and_towers:village_wooded_badlands",
		"towns_and_towers:wreckage_ocean",
		"trek:end/medium/end_city",
		"trek:nether/common/nether_pillar",
		"trek:nether/medium/overworld_leak_1",
		"trek:nether/medium/overworld_leak_2",
		"trek:overworld/common/cooking_pork",
		"trek:overworld/common/elven_pillars",
		"trek:overworld/common/frozen_remains",
		"trek:overworld/common/mushroom_house",
		"trek:overworld/common/ruins",
		"trek:overworld/common/small_desert_ruins",
		"trek:overworld/common/small_swamp_ruins",
		"trek:overworld/common/smoldering_altar",
		"trek:overworld/common/strange_stone",
		"trek:overworld/common/termite_hill",
		"trek:overworld/common/two_woods",
		"trek:overworld/common/well",
		"trek:overworld/common/well_pillager_small",
		"trek:overworld/medium/all_abandoned",
		"trek:overworld/medium/base_1",
		"trek:overworld/medium/base_2",
		"trek:overworld/medium/base_pillager",
		"trek:overworld/medium/beehive_house",
		"trek:overworld/medium/birch_fort",
		"trek:overworld/medium/birch_trade",
		"trek:overworld/medium/bone_dragon",
		"trek:overworld/medium/buried_village",
		"trek:overworld/medium/camp_1",
		"trek:overworld/medium/camp_2",
		"trek:overworld/medium/camp_3",
		"trek:overworld/medium/camp_4",
		"trek:overworld/medium/church",
		"trek:overworld/medium/claw_pillager",
		"trek:overworld/medium/claw_spike",
		"trek:overworld/medium/cold_hideout",
		"trek:overworld/medium/cold_red_trade",
		"trek:overworld/medium/dark_oak_trade",
		"trek:overworld/medium/desert_outpost",
		"trek:overworld/medium/desert_ranch",
		"trek:overworld/medium/destroyed_house",
		"trek:overworld/medium/dirt_hut",
		"trek:overworld/medium/enchanter",
		"trek:overworld/medium/explorer_cabin",
		"trek:overworld/medium/farm",
		"trek:overworld/medium/farm_pillager",
		"trek:overworld/medium/fort",
		"trek:overworld/medium/frozen_tree",
		"trek:overworld/medium/graveyard",
		"trek:overworld/medium/haunted_house",
		"trek:overworld/medium/hobbit_hole",
		"trek:overworld/medium/ice_fort",
		"trek:overworld/medium/igloo_village",
		"trek:overworld/medium/jungle_outpost",
		"trek:overworld/medium/jungle_trade",
		"trek:overworld/medium/jungle_treehouse",
		"trek:overworld/medium/lush_ice",
		"trek:overworld/medium/maison",
		"trek:overworld/medium/mangrove_watchtower",
		"trek:overworld/medium/oasis",
		"trek:overworld/medium/offshore_platform_pillager",
		"trek:overworld/medium/orbital",
		"trek:overworld/medium/pillager_old_camp",
		"trek:overworld/medium/pillager_weapons",
		"trek:overworld/medium/plains_cottage",
		"trek:overworld/medium/railroad",
		"trek:overworld/medium/ritual",
		"trek:overworld/medium/ruine_bateaux",
		"trek:overworld/medium/ruine_cabane",
		"trek:overworld/medium/ruine_tour",
		"trek:overworld/medium/ship_pillager",
		"trek:overworld/medium/small_pyramide",
		"trek:overworld/medium/small_red_trade",
		"trek:overworld/medium/snow_cottage",
		"trek:overworld/medium/snowman",
		"trek:overworld/medium/sorcerers_house",
		"trek:overworld/medium/spruce_camp",
		"trek:overworld/medium/spruce_cottage",
		"trek:overworld/medium/square_tower",
		"trek:overworld/medium/star_spike",
		"trek:overworld/medium/stelzen",
		"trek:overworld/medium/stonehedge",
		"trek:overworld/medium/strange_house",
		"trek:overworld/medium/street_vendor_pillager",
		"trek:overworld/medium/street_vendor_stall",
		"trek:overworld/medium/three_finger_ice",
		"trek:overworld/medium/tour",
		"trek:overworld/medium/tour_desert",
		"trek:overworld/medium/tower",
		"trek:overworld/medium/tower_of_ice",
		"trek:overworld/medium/underwater_sword",
		"trek:overworld/medium/wandering_trader_dark_oak",
		"trek:overworld/medium/wandering_trader_oak",
		"trek:overworld/medium/wandering_trader_spruce",
		"trek:overworld/medium/water_reservoir_pillager",
		"trek:overworld/medium/well_pillager_medium",
		"trek:overworld/medium/wild_stone",
		"trek:overworld/medium/witch_tower",
		"trek:overworld/rare/abandoned_castle_pillager",
		"trek:overworld/rare/castle",
		"trek:overworld/rare/elven_tree",
		"trek:overworld/rare/island_village_1",
		"trek:overworld/rare/maya",
		"trek:overworld/rare/mushroom_island",
		"trek:overworld/rare/pillager_mansion",
		"trek:overworld/rare/portal_sword",
		"trek:overworld/rare/pyramide_of_anubis",
		"trek:overworld/rare/sleepy_island",
		"trek:overworld/rare/sunken_city",
		"trek:overworld/rare/tower_island",
		"trek:overworld/rare/villager_castle",
		"trek:overworld/rare/villager_fortress",
		"trek:overworld/rare/villager_island",
		"trek:overworld/rare/wooden_manor",
		"trek:overworld/very_common/plains",
		"trek:overworld/very_common/rocks",
		"trek:overworld/very_rare/coves",
		"trek:overworld/very_rare/farm_island",
		"trek:overworld/very_rare/floating_farm_large",
		"trek:village/desert",
		"trek:village/mushroom",
		"trek:village/plains",
		"trek:village/savanna",
		"trek:village/snowy",
		"trek:village/swamp",
		"trek:village/taiga",
		"u_desert:badlands/ambient/geyser",
		"u_desert:badlands/ambient/skeleton/rib",
		"u_desert:badlands/ambient/skeleton/spine",
		"u_desert:badlands/ambient/termite_mound",
		"u_desert:desert/adventure/pillager_outpost/abandoned",
		"u_desert:desert/adventure/pillager_outpost/standard",
		"u_desert:desert/ambient/cactus/fork",
		"u_desert:desert/ambient/cactus/patch",
		"u_desert:desert/ambient/oasis/dried_up",
		"u_desert:desert/ambient/oasis/lively",
		"u_desert:desert/archeology/fossil/croc",
		"u_desert:desert/archeology/fossil/head",
		"u_desert:desert/archeology/fossil/skull/triceratops",
		"u_desert:desert/archeology/fossil/skull/tyrannosaurus",
		"u_desert:desert/archeology/ruin/house",
		"u_desert:desert/archeology/ruin/pit",
		"u_desert:desert/archeology/ruin/well",
		"u_sea:island/cold/glacier",
		"u_sea:island/warm/hill",
		"u_sea:island/warm/tower",
		"u_sea:lighthouse",
		"u_sea:raft/cold/cone_tide_breaker",
		"u_sea:raft/cold/tide_breaker",
		"u_sea:raft/cold/wide_tide_breaker",
		"u_sea:raft/temperate/beam",
		"u_sea:raft/temperate/box",
		"u_sea:raft/temperate/grid",
		"u_sea:raft/warm/cone_skipper",
		"u_sea:raft/warm/skipper",
		"u_sea:ship/cove",
		"u_sea:ship/hopper",
		"underground_bunkers:underground_bunker",
		"underwater_village:cold_big_gate",
		"underwater_village:cold_broken_house",
		"underwater_village:cold_fountain",
		"underwater_village:cold_gate",
		"underwater_village:dungeon",
		"underwater_village:library",
		"underwater_village:ruins",
		"underwater_village:shrine",
		"underwater_village:small_gate",
		"underwater_village:temple",
		"underwater_village:temple_broken",
		"underwater_village:temple_ruins",
		"underwater_village:tower",
		"underwater_village:warm_big_gate",
		"underwater_village:warm_broken_house",
		"underwater_village:warm_fountain",
		"underwater_village:warm_gate",
		"wabi_sabi_structures:abandoned_small_castle",
		"wabi_sabi_structures:badlands_dwelling",
		"wabi_sabi_structures:bamboo_firework_site",
		"wabi_sabi_structures:basalt_castle",
		"wabi_sabi_structures:basalt_factory_ruin",
		"wabi_sabi_structures:bat_monolith",
		"wabi_sabi_structures:bee_farm_cherry",
		"wabi_sabi_structures:bee_farm_forest",
		"wabi_sabi_structures:beetroot_patch",
		"wabi_sabi_structures:birch_mushroom_cave",
		"wabi_sabi_structures:candlemaker_house",
		"wabi_sabi_structures:carrot_patch",
		"wabi_sabi_structures:chorus_orchard",
		"wabi_sabi_structures:concrete_mill_ruins_desert",
		"wabi_sabi_structures:concrete_mill_ruins_shore",
		"wabi_sabi_structures:dark_witch_keep",
		"wabi_sabi_structures:effigy_patch_forest",
		"wabi_sabi_structures:effigy_patch_jungle",
		"wabi_sabi_structures:effigy_patch_mushroom",
		"wabi_sabi_structures:effigy_patch_savanna",
		"wabi_sabi_structures:effigy_patch_swamp",
		"wabi_sabi_structures:ender_claw",
		"wabi_sabi_structures:firewatch_tower",
		"wabi_sabi_structures:forgotten_remnants",
		"wabi_sabi_structures:frost_reactor_plant",
		"wabi_sabi_structures:gallows",
		"wabi_sabi_structures:hellish_orphanage",
		"wabi_sabi_structures:hide_tannery_cherry",
		"wabi_sabi_structures:hide_tannery_oak",
		"wabi_sabi_structures:howlers_garrison",
		"wabi_sabi_structures:ice_shanty",
		"wabi_sabi_structures:infested_castle_stony",
		"wabi_sabi_structures:lighthouse",
		"wabi_sabi_structures:llama_sanctuary_hills",
		"wabi_sabi_structures:llama_sanctuary_plateau",
		"wabi_sabi_structures:lost_foot",
		"wabi_sabi_structures:lumpy_tower",
		"wabi_sabi_structures:marine_observation_hub",
		"wabi_sabi_structures:melon_field",
		"wabi_sabi_structures:melon_patch",
		"wabi_sabi_structures:memorial_of_tonkis",
		"wabi_sabi_structures:monster_egg",
		"wabi_sabi_structures:monster_egg_banquet",
		"wabi_sabi_structures:moss_blob",
		"wabi_sabi_structures:mossy_roof_house",
		"wabi_sabi_structures:mossy_roof_shed",
		"wabi_sabi_structures:muddy_badlands_well",
		"wabi_sabi_structures:mushroom_house",
		"wabi_sabi_structures:obsidian_egg",
		"wabi_sabi_structures:old_fort",
		"wabi_sabi_structures:old_stable",
		"wabi_sabi_structures:old_tiny_house",
		"wabi_sabi_structures:potato_patch",
		"wabi_sabi_structures:pumpkin_field",
		"wabi_sabi_structures:pumpkin_patch",
		"wabi_sabi_structures:river_boat",
		"wabi_sabi_structures:rot_tree",
		"wabi_sabi_structures:sand_ship",
		"wabi_sabi_structures:shrine_of_preservation",
		"wabi_sabi_structures:sphinx_hidey_hole_icy",
		"wabi_sabi_structures:sphinx_hidey_hole_sandy",
		"wabi_sabi_structures:spider_cellar",
		"wabi_sabi_structures:spruce_berry_farm",
		"wabi_sabi_structures:spruce_cabin",
		"wabi_sabi_structures:strider_stable",
		"wabi_sabi_structures:sunken_steamboat",
		"wabi_sabi_structures:tall_birch_house",
		"wabi_sabi_structures:totem_pole",
		"wabi_sabi_structures:tree_cage",
		"wabi_sabi_structures:turtle_soup_kitchen",
		"wabi_sabi_structures:vigilante_fort",
		"wabi_sabi_structures:wandering_trader_cart_cold",
		"wabi_sabi_structures:wandering_trader_cart_temperate",
		"wabi_sabi_structures:warped_ender_claw",
		"wabi_sabi_structures:water_tower_dark_oak",
		"wabi_sabi_structures:water_tower_forest",
		"wabi_sabi_structures:water_tower_oak",
		"wabi_sabi_structures:water_tower_savanna",
		"wabi_sabi_structures:water_tower_spruce",
		"wabi_sabi_structures:wheat_patch",
		"wabi_sabi_structures:woody_camp",
		"wabi_sabi_structures:xocolatl_farm",
		"wabi_sabi_structures:zen_chair_museum"
	));

	public static final SortedSet<String> defaultUndergroundStructures = new TreeSet<>(Arrays.asList(
		"ati_structures:pufferfish_cave",
		"ati_structures:rotting_temple_underground",
		"ati_structures:sculk_deposit",
		"ati_structures:silverfish_nest",
		"ati_structures:spider_nest",
		"ati_structures:underground_monument",
		"ati_structures:underwater_dungeon",
		"ati_structures:warden_monument",
		"ati_structures:wither_cavern",
		"betterdungeons:skeleton_dungeon",
		"betterdungeons:small_dungeon",
		"betterdungeons:small_nether_dungeon",
		"betterdungeons:spider_dungeon",
		"betterdungeons:zombie_dungeon",
		"bettermineshafts:mineshaft_acacia",
		"bettermineshafts:mineshaft_desert",
		"bettermineshafts:mineshaft_dripstone",
		"bettermineshafts:mineshaft_ice",
		"bettermineshafts:mineshaft_jungle",
		"bettermineshafts:mineshaft_lush",
		"bettermineshafts:mineshaft_mesa",
		"bettermineshafts:mineshaft_mushroom",
		"bettermineshafts:mineshaft_oak",
		"bettermineshafts:mineshaft_overgrown",
		"bettermineshafts:mineshaft_red_desert",
		"bettermineshafts:mineshaft_spruce",
		"bettermineshafts:mineshaft_spruce_snowy",
		"betterstrongholds:stronghold",
		"bosses_of_mass_destruction:gauntlet_arena",
		"create_ltab:cave_ruins",
		"create_structures_arise:create_dungeon_base",
		"dungeons_arise:foundry",
		"dungeons_arise:mining_complex",
		"dungeons_arise:mining_system",
		"dungeons_arise:plague_asylum",
		"feur_extension_fossil:fossil_hand",
		"formationsnether:basalt_hut",
		"formationsnether:ore_shard",
		"hopo:mineshaft/acacia_mineshaft",
		"hopo:mineshaft/bamboo_mineshaft",
		"hopo:mineshaft/biomes/dripstone_mineshaft",
		"hopo:mineshaft/biomes/lush_mineshaft",
		"hopo:mineshaft/birch_mineshaft",
		"hopo:mineshaft/cherry_mineshaft",
		"hopo:mineshaft/deepslate_mineshaft",
		"hopo:mineshaft/jungle_mineshaft",
		"hopo:mineshaft/mangrove_mineshaft",
		"hopo:mineshaft/mud_mineshaft",
		"hopo:mineshaft/oak_mineshaft",
		"hopo:mineshaft/spruce_mineshaft",
		"hopo:mineshaft/stone_mineshaft",
		"hopo:portal/overworld/portal_deepslate",
		"hopo:portal/overworld/portal_dripstone",
		"hopo:portal/overworld/portal_lush",
		"minecraft:ancient_city",
		"minecraft:buried_treasure",
		"minecraft:fortress",
		"minecraft:mineshaft",
		"minecraft:mineshaft_mesa",
		"minecraft:nether_fossil",
		"minecraft:trail_ruins",
		"minecraft:trial_chambers",
		"mvs:mineshaft",
		"mythsandlegends:sepulcrum_ignitum",
		"nova_structures:deepslate_camp",
		"nova_structures:illager_hideout",
		"nova_structures:lone_citadel",
		"nova_structures:nether_keep",
		"nova_structures:nether_port",
		"nova_structures:piglin_donjon",
		"nova_structures:toxic_lair",
		"nova_structures:trident_trial_monument",
		"nova_structures:undead_crypt",
		"nova_structures:underground_house",
		"philipsruins:ancient_dungeon",
		"philipsruins:lost_soul_city",
		"philipsruins:lost_soul_dungeon",
		"philipsruins:underground_structures",
		"repurposed_structures:bastion_underground",
		"repurposed_structures:mineshaft_birch",
		"repurposed_structures:mineshaft_dark_forest",
		"repurposed_structures:mineshaft_desert",
		"repurposed_structures:mineshaft_end",
		"repurposed_structures:mineshaft_icy",
		"repurposed_structures:mineshaft_jungle",
		"repurposed_structures:mineshaft_ocean",
		"repurposed_structures:mineshaft_savanna",
		"repurposed_structures:mineshaft_stone",
		"repurposed_structures:mineshaft_swamp",
		"repurposed_structures:mineshaft_taiga",
		"repurposed_structures:monument_nether",
		"repurposed_structures:stronghold_end",
		"supplementaries:road_sign",
		"totw_modded:ocean",
		"totw_modded:ocean_warm",
		"towns_and_towers:pillager_outpost_ocean",
		"towns_and_towers:village_ocean",
		"towns_and_towers:wreckage_ocean",
		"trek:nether/common/nether_pillar",
		"underground_bunkers:underground_bunker",
		"wabi_sabi_structures:bat_monolith",
		"wabi_sabi_structures:forgotten_remnants",
		"wabi_sabi_structures:hellish_orphanage",
		"wabi_sabi_structures:shrine_of_preservation",
		"wabi_sabi_structures:warped_ender_claw"
	));
}
